#!/bin/sh
/sbin/su-exec garminbackup /home/garminbackup/gcexport.py -d /home/garminbackup/data --count 3 --format original --unzip --originaltime --username "your.email@mail.com" --password "your.s3cret" 2>&1 
